#!/usr/bin/python

import urllib2
import json
import argparse

# TODO: run through the data to find the right sizes
formatter='{:>15} {:>10} {}'

def printStream(stream):
	count=stream['count']
	size=stream['size']
	sizeunit='B '
	if size>10000:
		size=size/1024
		sizeunit='KB'
	if size>10000:
		size=size/1024
		sizeunit='MB'
	if size>10000:
		size=size/1024
		sizeunit='GB'

	print formatter.format(stream['count'],str(size)+' '+sizeunit,stream['topic'])

def listStreams(args):
	# TODO: make it possible to specific http or https in the hostname
	response = urllib2.urlopen('http://'+args.host+':'+args.port+'/stream/')
	data = json.loads(response.read())

	# print formatter.format('topic','count','size   ')	
	for stream in data:
		printStream(stream)

parser = argparse.ArgumentParser(description='List all StroomData streams on a host')

parser.add_argument('--host', dest='host', help='Specify a specific host', default="127.0.0.1")
parser.add_argument('--port', dest='port', help='Specify a specific port', default="8080")

args = parser.parse_args()

listStreams(args)