#!/usr/bin/python

import urllib2
import json
import argparse
import sys


pageSize=10

def writeObject(args,stringData):
	request = urllib2.Request('http://'+args.host+':'+args.port+'/stream/'+args.stream)
	request.add_header('Content-Type','application/json')
	response = urllib2.urlopen(request,stringData)


parser = argparse.ArgumentParser(description='Write standard in to a StroomData stream on a host')

parser.add_argument('--host', dest='host', help='Specify a specific host', default="127.0.0.1")
parser.add_argument('--port', dest='port', help='Specify a specific port', default="8080")
parser.add_argument('stream', help='Specify which stream to write to')

args = parser.parse_args()

#TODO: we should read and write in batches ... maybe collect the input in a list?

for line in sys.stdin:
	#TODO: skip blank lines
    writeObject(args,line)